CREATE TABLE EMPLEADO(
    cod_empleado         NUMBER PRIMARY KEY,
    nombre              VARCHAR2(100) NOT NULL,
    fechaNacimiento     DATE NOT NULL,
    tlfContacto         VARCHAR2(20) NOT NULL,
    correoElectronico   VARCHAR2(100) NOT NULL,
    codContrato         NUMBER NOT NULL,
    cod_departamento     NUMBER NOT NULL,

    -- Claves foráneas
    CONSTRAINT fk_empleado_contrato 
        FOREIGN KEY (cod_contrato) 
        REFERENCES contrato(cod_contrato),

    CONSTRAINT fk_empleado_departamento 
        FOREIGN KEY (cod_departamento) 
        REFERENCES departamento(cod_departamento)
);


CREATE TABLE DEPARTAMENTO(
    cod_departamento   NUMBER PRIMARY KEY,
    nombre             VARCHAR2(100) NOT NULL,
    descripcion        VARCHAR2(500)
);


CREATE TABLE OBRA_DE_ARTE (
    cod_obra             NUMBER PRIMARY KEY,
    nombre               VARCHAR2(100) NOT NULL,
    autor                VARCHAR2(100),
    fecha_creacion       DATE,
    fecha_adquisicion    DATE,
    tipo VARCHAR2(50) CHECK (tipo IN ('Cuadro', 'Escultura', 'Fotografía', 'Alfarería'))
    estilo_artistico     VARCHAR2(100),
    estilo_historico     VARCHAR2(100),
    descripcion          VARCHAR2(500),
    imagen               BLOB,
    cod_sala             NUMBER,
    cod_autor	        NUMBER,

    CONSTRAINT fk_obra_sala 
        FOREIGN KEY (cod_sala) 
        REFERENCES sala(cod_sala),
 
    CONSTRAINT fk_obra_autor 
        FOREIGN KEY (cod_autor)
        REFERENCES autor(cod_autor)

);


CREATE TABLE SALA (
    cod_sala       NUMBER PRIMARY KEY,
    nombre         VARCHAR2(100) NOT NULL,
    localizacion   VARCHAR2(100),
    descripcion    VARCHAR2(255)
);

CREATE TABLE ACTIVIDADES (
    codigo_actividad NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion TEXT NOT NULL,
    fecha_inicio DATE NOT NULL
    fecha_fin DATE DEFAULT NOT NULL
    publico_objetivo VARCHAR2(100) NOT NULL,
    cod_empleado NUMBER NOT NULL,  
    cod_externo NUMBER NOT NULL,  
);


CREATE TABLE VISITA(
    cod_actividad NUMBER PRIMARY KEY,
    cupo_maximo NUMBER NOT NULL,
    idioma VARCHAR2(50) NOT NULL,
   tipo VARCHAR2(20) CHECK (tipo IN ('Guiada', 'Virtual')),
   CONSTRAINT fk_visita_actividades FOREIGN KEY (cod_actividad) REFERENCES ACTIVIDADES(codigo_actividad)
);


CREATE TABLE EXPOSICION (
    cod_actividad NUMBER PRIMARY KEY,
    tematica VARCHAR2(100) NOT NULL,
    numero_obras NUMBER NOT NULL,
    cod_sala NUMBER NOT NULL,
    CONSTRAINT chk_tipo_expo CHECK (tipo IN ('Online', 'Física')),
    CONSTRAINT fk_exposicion_actividades FOREIGN KEY (cod_actividad) REFERENCES ACTIVIDADES(codigo_actividad)
);


CREATE TABLE EXTERNOS(
    codigo_externo NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    telefono_contacto VARCHAR2(20) NOT NULL,
    correo_electronico VARCHAR2(100) NOT NULL,
    cod_actividad NUMBER NOT NULL,
);


CREATE TABLE VISITANTES (
    codigo_visitante NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    telefono_contacto VARCHAR2(20) NOT NULL,
    correo_electronico VARCHAR2(100) NOT NULL
);



CREATE TABLE ENTRADAS(
    codigo_entrada NUMBER PRIMARY KEY,
    precio DECIMAL(10, 2) NOT NULL,
    fecha DATE NOT NULL
    cod_cliente NUMBER NOT NULL,
    cod_venta NUMBER NOT NULL,
    tipo VARCHAR2(20)  CHECK (tipo IN ('Físico', 'Online')),

    CONSTRAINT fk_entradas_clientes FOREIGN KEY (cod_cliente) REFERENCES VISITANTES(codigo_visitante),
    CONSTRAINT fk_entradas_ventas FOREIGN KEY (cod_venta) REFERENCES VENTA(cod_venta)
);



CREATE TABLE CONTRATO (
    cod_contrato   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fecha_ini      DATE NOT NULL,
    fecha_fin      DATE DEFAULT NULL,
    sueldo         NUMBER(10, 2) NOT NULL,
    jornada_laboral VARCHAR2(50) NOT NULL,
    estado         VARCHAR2(20) NOT NULL,
    cod_empleado   INTEGER NOT NULL,

    CONSTRAINT fk_cod_empleado FOREIGN KEY (cod_empleado) REFERENCES empleado(id)
);

CREATE TABLE VENTA (
    cod_venta     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fecha         DATE NOT NULL,
    cod_empleado  INTEGER NOT NULL,

    CONSTRAINT fk_ref_empleado FOREIGN KEY (cod_empleado) REFERENCES empleado(id)
);

CREATE TABLE ROL (
    cod_rol        NUMBER NOT NULL,
    nombre         VARCHAR2(50) NOT NULL,
    descripcion    VARCHAR2(255),

    CONSTRAINT pk_roles PRIMARY KEY (cod_rol),
    CONSTRAINT fk_ref_empleado FOREIGN KEY (cod_rol) REFERENCES empleado(id)
);

CREATE TABLE AUTORES (
    cod_autor           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR2(100) NOT NULL,
    pais_origen         VARCHAR2(50),
    fecha_nacimiento    DATE,
    fecha_muerte        DATE,
    num_obras           INTEGER,
    estilo_principal    VARCHAR2(100)
);
