# Usamos la imagen base de Oracle XE
FROM gvenzl/oracle-xe:latest

# Establece las variables de entorno necesarias para Oracle
ENV ORACLE_SID=XEPDB1

# Exponemos los puertos para acceder a Oracle y al SQL Developer
EXPOSE 1521 5500

